framework:
    cache:
        prefix_seed: homullus/kaputt
        app: cache.adapter.filesystem
        pools:
            app.cache.weather:
                adapter: cache.app
                default_lifetime: 43200 # 12 hours
