version: "3.7"

services:

    nginx:
#        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - macura:/app/macura:ro
            - nada:/app/nada:ro
        ports:
            - ${HTTP_PORT}:80

    php:
        volumes:
            - macura:/app/macura:delegated

    node:
        volumes:
            - nada:/app/nada:delegated
            - nada-node-modules:/app/nada/node_modules # Ignore
            - /app/nada/.git # Ignore

volumes:
    macura:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/../app/macura
            o: bind
    nada:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/../app/nada
            o: bind
    nada-node-modules:
