version: "3.7"

services:

    nginx:
        container_name: kaputt_nginx
        build:
            context: ../
            dockerfile: ./Docker/nginx/Dockerfile
            target: ${ENV}
            args:
                - SSL_CERTS_PATH=${SSL_CERTS_PATH}
        restart: always
        volumes:
            - nada:/app/nada:ro
        ports:
            - ${HTTPS_PORT}:443
        networks:
            - kaputt

    php:
        container_name: kaputt_php
        build:
            context: ../
            dockerfile: ./Docker/php/Dockerfile
            target: ${ENV}
            args:
                - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
        environment:
            APP_ENV: ${ENV}
            APP_DEBUG: ${SYMFONY_APP_DEBUG}
            DARKSKY_API_KEY: ${DARKSKY_API_KEY}
        entrypoint: /app/entrypoint.sh
        restart: always
        networks:
            - kaputt

    node:
        container_name: kaputt_node
        build:
            context: ../
            dockerfile: ./Docker/node/Dockerfile
            target: ${ENV}
        entrypoint: /app/entrypoint.sh
        volumes:
            - nada:/app/nada:delegated
            - nada-node-modules:/app/nada/node_modules # Ignore
            - /app/nada/.git # Ignore
        environment:
            NODE_ENV: ${ENV}
        networks:
            - kaputt

networks:
    kaputt:
        driver: bridge

volumes:
    nada:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/../app/nada
            o: bind
    nada-node-modules:
